### ISSUE TITLE
Add Pods folder to gitignore

### ISSUE THREAD

**Issue by JeffGuKang** [JeffGuKang/react-native-tutorial#131]
React Native > 0.60 started to ignore `iOS/Pods` folder from git. 
It consumes a lot of storage and do not need anymore to track by git as `node_modules`.
Thus, add `Pods` to `.gitignore` and delete all cache from git.

**Comment by sonypark** [comment]
I think `ios/Pods` is already added to `.gitignore` in each project file. Is there any `.gitignore` file which needs to add `Pods`?

```
# CocoaPods
/ios/Pods/
```

**Comment by JeffGuKang** [comment]
@sonypark You are right. All RN versions of all examples are already over 0.60.0. We do not need any action.
