### ISSUE TITLE
[Tutorial/State] Fix redux-tutorial docs

### ISSUE THREAD

**Issue by jinsunee** [JeffGuKang/react-native-tutorial#189]
1. To make it easier to understand, I will supplement my lack of explanation.
2. I will correct the misused part of the mark-up grammar. 
 -> Some parts were printed like '###title' because they did not write space. 
 -> I also found a part that doesn't fit the font size. 
  -> I'm going to fix this whole thing!

**Comment by JeffGuKang** [comment]
How to fix the docs? Description will be help to the others.
