### ISSUE TITLE
Create Intro for docs and Change location 'contribution.md'

### ISSUE THREAD

**Issue by jinsunee** [JeffGuKang/react-native-tutorial#196]
- Create Intro for docs.
- Change the location of `contribution.md` from `/docs/contribution.md` to `/contribution.md`.

**Comment by JeffGuKang** [comment]
The 'docs/Contribution.md' should be moved to root and need to change all lowercase. Refer the [official guide](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors).
