### ISSUE TITLE
더미 데이터로 사용 되는 api 가 404 발생합니다.

### ISSUE THREAD

**Issue by sigpankyo** [JeffGuKang/react-native-tutorial#202]
https://jeffgukang.github.io/react-native-tutorial/docs/sample-apps/coininfo-list/09-real-data/real-data-kr.html

이부분을 보고 열심히 따라하는 1인 입니다.
헌데 더미로 사용중인 api 가 404가 발생되어 더이상 학습을 진행을 못하고 있는데요.
혹시 이부분 데이터 원형을 알려주시면 내 로컬에 만들어 사용 하겠습니다.

아니면 해당 api 을 다음 학습자를 위해 살려 주시면 정말로 감사 하겠습니다.
https://api.coinmarketcap.com/v1/ticker/?limit=${limit}
https://api.coinmarketcap.com/v1/ticker/?limit=10

**Comment by JeffGuKang** [comment]
@sigpankyo 
더미 데이터는 [다음](
https://jeffgukang.github.io/react-native-tutorial/docs/sample-apps/coininfo-list/08-dummy-into-coinitem-component/dummy-into-coinitem-component-kr.html)과 같은 형식입니다. 


Api 의 경우 제공자의 정책으로 인해 가입하고 쓰셔야 하는 것으로 바뀌었습니다. https://coinmarketcap.com/api/documentation/v1/ 를 참고하시면 됩니다.
