### ISSUE TITLE
import 오류

### ISSUE THREAD

**Issue by petersoo** [JeffGuKang/react-native-tutorial#204]
경로 : Basic(한글)/ 할 일 목록 앱 만들기 / 6. TodoInsert 컴포넌트

App.js에 TodoInsert를 import 하면 아래와 같이 뜨는데 혹시 아실까요? 

[오류내용]
TodoList' is declared but its value is never read.ts(6133)

[이미지 첨부]
![임포트_오류_최종](https://user-images.githubusercontent.com/41869655/108818300-82b46180-75fc-11eb-9b47-b9f2d369e97c.jpg)

**Comment by jinsunee** [comment]
TodoInsert 를 import 해왔지만 해당 파일에서 사용되지 않아서 생기는 경고메세지의 에러인 것 같아요. 지워보시고 실행시켜보시겠어요???

**Comment by petersoo** [comment]
지우고 실행하면 이상없이 잘 됩니다. 

TodoInsert import 하면 저렇게 경고 메시지 뜨고.. 
시뮬레이터는 동일하게 ADD가 추가되지 않된 상태로 뜹니다. ㅠ
[
![임포트_오류_최종(2)](https://user-images.githubusercontent.com/41869655/108821235-a5487980-7600-11eb-83bd-db3f4667d344.JPG)
](url)

**Comment by jinsunee** [comment]
위에 보여주신 코드(App.js)로 실행시켰을 때 결과가 원하는대로 안나오는 이유는 TodoInsert의 문제라고 생각하시는 것보다 `return ();` 안에 있는 코드가 아직 완성이 안되어있다고 생각해보시고 접근하셔야할 것 같습니다!

1. Todo item을 입력받는 TextInput에 무언가 값을 담을 때 필요한 `value`, `onChangeText()`와 같은 props가 없는 것으로 보여요!
2. 마찬가지로, button도 onPress 했을 때 아이템이 추가되는 함수가 구현되어있지 않고
3. TodoList를 loop로 돌며 TodoItem을 하나씩 렌더링 해줄 부분으로 보여지는 `<Text>todoList</Text>` 이부분도 완성되지 않은 것으로 보입니다.

## 결론적으로,
TodoInsert는 지우셔도 될 것 같고 코드를 수정해보시는게 어떨까요???
아니면 [여기](https://github.com/JeffGuKang/react-native-tutorial/tree/master/Examples/BasicTutorial/BasicFeatures/TodoList/components)에 나와있는대로 그대로 복사해서 붙여넣기한 후 코드를 돌려보시고 확인해보시며 익혀보시는 것도 좋은 방법일 것 같습니다.😊

**Comment by jinsunee** [comment]
아 참고로, 저 에러는 typescript 설정에서 
`import는 해왔지만 사용하지 않는다면 에러를 표시하자` 이런 뜻인데, 당장 프로그램이 돌아가는데는 지장 없을 것 같으니 `Quick Fix`를 눌러주셔도 큰 문제는 없을 것 같아요.

**Comment by petersoo** [comment]
말씀하신데로 return 부분이 잘못되어 있었네요 ! ㅎㅎ 
다시 지우고 하나씩 다시 JS 만들어서 발견했네요 ㅠ 
TodoInsert 태그가 없어 선언이 안되어 떴었네요!! 
자세한 설명 감사합니다!! ^^
