### ISSUE TITLE
[Tutorial/Basic] Additional Basic Contents

### ISSUE THREAD

**Issue by chococrunch2021** [JeffGuKang/react-native-tutorial#24]
basic tutorials of additional contents

**Comment by sonypark** [comment]
![image](https://user-images.githubusercontent.com/34808501/66805026-ef2a4580-ef5e-11e9-9ee4-5b607ede0976.png)

@Haerang94 

I think the documents in these folder has an incorrect grandparent folder name, please check it and correct the name please.

I think `grand_parent` should be `Basic`, not `basic-tutorial`.

```
---
layout: default
title: 1. basic-settings
parent: basic-functions
grand_parent: basic-tutorial
nav_order: 1
---
```

**Comment by chococrunch2021** [comment]
Another issue will be added
