### ISSUE TITLE
[Tutorial/Basic] Complete RN Todolist based on basic features

### ISSUE THREAD

**Issue by sonypark** [JeffGuKang/react-native-tutorial#46]
## Features to be used on this app
- Props
- State
- Style
- Height and Width
- Layout with Flexbox
- Handling Text Input
- Handling Touches
- ScrollView
- List Views
- Networking
- etc

**Comment by qkreltms** [comment]
Well, list of Advanced features already has Networking session which on your list so you don't have to add it.

**Comment by sonypark** [comment]
Okay. Thanks for letting me know
